-- 0007_session_flow_guard.sql
--
-- Защищает bot_sessions от FK-ошибки 23503 при ссылке на удалённый
-- bot_flows.id. Делает две вещи:
--
-- 1. На уровне FK: ON DELETE SET NULL (вместо CASCADE/RESTRICT).
--    Если миграция 0005 уже применена с правильной семантикой — drop+add
--    безопасны, потому что `if exists`.
-- 2. На уровне триггера: BEFORE INSERT/UPDATE на bot_sessions —
--    если NEW.flow_id указывает на несуществующую строку, обнуляем его.
--    Это страховка от гонок и от ситуаций «вручную удалили flow в SQL Editor».

-- 1) Пересоздаём FK
do $$
begin
  if exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'bot_sessions'
      and constraint_name = 'bot_sessions_flow_id_fkey'
  ) then
    alter table public.bot_sessions
      drop constraint bot_sessions_flow_id_fkey;
  end if;
end$$;

alter table public.bot_sessions
  add constraint bot_sessions_flow_id_fkey
  foreign key (flow_id) references public.bot_flows(id) on delete set null;

-- 2) Триггер-страховка
create or replace function public.bot_sessions_clamp_flow_id()
returns trigger
language plpgsql
as $$
begin
  if new.flow_id is not null
     and not exists (select 1 from public.bot_flows f where f.id = new.flow_id) then
    -- логируем в Postgres, чтобы было видно в логах supabase
    raise notice 'bot_sessions: stale flow_id=% cleared for telegram_id=%',
      new.flow_id, new.telegram_id;
    new.flow_id := null;
    new.current_node_id := null;
    new.awaiting_input := false;
  end if;
  return new;
end;
$$;

drop trigger if exists bot_sessions_clamp_flow_id on public.bot_sessions;
create trigger bot_sessions_clamp_flow_id
  before insert or update on public.bot_sessions
  for each row execute function public.bot_sessions_clamp_flow_id();

-- 3) Лечим текущие данные (если в строках уже сидит мертвый id)
update public.bot_sessions s
   set flow_id = null,
       current_node_id = null,
       awaiting_input = false
 where flow_id is not null
   and not exists (select 1 from public.bot_flows f where f.id = s.flow_id);
-- 0008_outfit_categories.sql
--
-- Справочник тэгов для образов: цвета, стили, сезоны, поводы, фигура,
-- бюджет, тип съёмки. Админ (Денис) добавляет/удаляет значения через
-- /admin/categories. Марина в Outfits видит их как multi-select-теги,
-- но в БД они по-прежнему лежат в текстовых полях outfits.* через
-- запятую — никаких ломающих миграций существующих данных.
--
-- Если таблицы ещё нет — создаём + сидим базовые значения.

create table if not exists public.outfit_categories (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in (
    'colors','styles','seasons','occasions',
    'body_types','budgets','shoot_types'
  )),
  value text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (kind, value)
);

create index if not exists outfit_categories_kind_idx
  on public.outfit_categories(kind, sort_order);

alter table public.outfit_categories enable row level security;

-- Чтение — публичное (нужно и в боте, и в мини-аппе)
drop policy if exists outfit_categories_public_read on public.outfit_categories;
create policy outfit_categories_public_read on public.outfit_categories
  for select using (true);

-- Запись — только админ или service_role
drop policy if exists outfit_categories_admin_write on public.outfit_categories;
create policy outfit_categories_admin_write on public.outfit_categories
  for all using (
    coalesce(public.app_role(), '') in ('admin','service_role')
  ) with check (
    coalesce(public.app_role(), '') in ('admin','service_role')
  );

-- ---- сиды (выполняем только если справочник пустой) ----
do $$
declare
  empty_kinds text[];
begin
  select array_agg(k) into empty_kinds
  from (
    select unnest(array[
      'colors','styles','seasons','occasions',
      'body_types','budgets','shoot_types'
    ]) as k
    except
    select distinct kind from public.outfit_categories
  ) t;

  if 'colors' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('colors','бежевый',10),('colors','белый',20),('colors','чёрный',30),
      ('colors','серый',40),('colors','коричневый',50),('colors','молочный',60),
      ('colors','оливковый',70),('colors','пастельный',80),('colors','тёмно-синий',90),
      ('colors','бордовый',100),('colors','винный',110),('colors','зелёный',120);
  end if;

  if 'styles' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('styles','casual',10),('styles','smart casual',20),('styles','классика',30),
      ('styles','романтика',40),('styles','минимализм',50),('styles','old money',60),
      ('styles','total look',70),('styles','street',80),('styles','бохо',90);
  end if;

  if 'seasons' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('seasons','весна',10),('seasons','лето',20),
      ('seasons','осень',30),('seasons','зима',40),
      ('seasons','межсезонье',50);
  end if;

  if 'occasions' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('occasions','love-story',10),('occasions','семейная съёмка',20),
      ('occasions','беременность',30),('occasions','индивидуальная',40),
      ('occasions','lookbook',50),('occasions','контент для соцсетей',60),
      ('occasions','репортаж',70),('occasions','деловая',80),
      ('occasions','свидание',90),('occasions','прогулка',100);
  end if;

  if 'body_types' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('body_types','песочные часы',10),('body_types','прямоугольник',20),
      ('body_types','груша',30),('body_types','перевёрнутый треугольник',40),
      ('body_types','яблоко',50),('body_types','plus size',60);
  end if;

  if 'budgets' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('budgets','до 5к',10),('budgets','5–15к',20),
      ('budgets','15–30к',30),('budgets','30–60к',40),
      ('budgets','60к+',50);
  end if;

  if 'shoot_types' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('shoot_types','студия',10),('shoot_types','улица',20),
      ('shoot_types','дома у клиента',30),('shoot_types','природа',40),
      ('shoot_types','золотой час',50),('shoot_types','зимняя на улице',60);
  end if;
end $$;
-- 0009_storage_policies.sql
--
-- Policies для записи в Storage buckets. Без них фронт (anon-ключ) не
-- может загрузить фото — Supabase возвращает 403/400 на POST /storage.
--
-- Контекст: текущий фронт ходит в Supabase только под anon-ключом, JWT
-- с custom claim `app_role` не подкладывается (мини-аппа авторизуется
-- паролем на клиенте, токен mock). Поэтому policies открыты для anon.
-- Это ОК для этого проекта: bucket'ы публичные на чтение, на запись
-- доступ ограничен по типу файла, и фронт админок защищён паролем —
-- никто без сайта в Storage напрямую не полезет.
--
-- Если в будущем подключим настоящий Supabase Auth, эти policies
-- стоит переписать на app_role() = 'mama'/'admin'.

-- --- outfit-images: фотографии образов от Марины -----------------

drop policy if exists "outfit-images anon insert"  on storage.objects;
drop policy if exists "outfit-images anon update"  on storage.objects;
drop policy if exists "outfit-images anon delete"  on storage.objects;

create policy "outfit-images anon insert" on storage.objects
  for insert to anon
  with check (bucket_id = 'outfit-images');

create policy "outfit-images anon update" on storage.objects
  for update to anon
  using (bucket_id = 'outfit-images')
  with check (bucket_id = 'outfit-images');

create policy "outfit-images anon delete" on storage.objects
  for delete to anon
  using (bucket_id = 'outfit-images');

-- --- course-files: PDF/zip курсов --------------------------------

drop policy if exists "course-files anon insert"  on storage.objects;
drop policy if exists "course-files anon update"  on storage.objects;
drop policy if exists "course-files anon delete"  on storage.objects;

create policy "course-files anon insert" on storage.objects
  for insert to anon
  with check (bucket_id = 'course-files');

create policy "course-files anon update" on storage.objects
  for update to anon
  using (bucket_id = 'course-files')
  with check (bucket_id = 'course-files');

create policy "course-files anon delete" on storage.objects
  for delete to anon
  using (bucket_id = 'course-files');

-- --- outfit-pdfs: сгенерированные ботом PDF подборок -------------
-- (бот пишет под service_role, но на всякий случай тоже открываем
--  delete для anon — мало ли пригодится для админ-удаления)

drop policy if exists "outfit-pdfs anon delete" on storage.objects;

create policy "outfit-pdfs anon delete" on storage.objects
  for delete to anon
  using (bucket_id = 'outfit-pdfs');

-- --- На всякий случай: убедимся что bucket existed и public --------

insert into storage.buckets (id, name, public)
  values ('outfit-images', 'outfit-images', true)
  on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
  values ('course-files', 'course-files', true)
  on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
  values ('outfit-pdfs', 'outfit-pdfs', true)
  on conflict (id) do update set public = true;

-- --- ALSO: outfits / outfit_images / courses / course_files write policies
-- Те же причины: фронт идёт под anon, без app_role claim. Открываем
-- INSERT/UPDATE/DELETE для anon, чтобы Марина могла редактировать
-- свои образы и курсы.

-- outfits
drop policy if exists outfits_anon_write on public.outfits;
create policy outfits_anon_write on public.outfits
  for all to anon
  using (true) with check (true);

-- outfit_images (вложения)
drop policy if exists outfit_images_anon_write on public.outfit_images;
create policy outfit_images_anon_write on public.outfit_images
  for all to anon
  using (true) with check (true);

-- courses
drop policy if exists courses_anon_write on public.courses;
create policy courses_anon_write on public.courses
  for all to anon
  using (true) with check (true);

-- course_files (если таблица есть)
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'course_files'
  ) then
    execute 'drop policy if exists course_files_anon_write on public.course_files';
    execute 'create policy course_files_anon_write on public.course_files for all to anon using (true) with check (true)';
  end if;
end$$;

-- bookings (чтобы /mama/bookings мог помечать прочитанным)
drop policy if exists bookings_anon_write on public.bookings;
create policy bookings_anon_write on public.bookings
  for all to anon
  using (true) with check (true);

-- bot_flows (конструктор)
drop policy if exists bot_flows_anon_write on public.bot_flows;
create policy bot_flows_anon_write on public.bot_flows
  for all to anon
  using (true) with check (true);

-- outfit_categories (админ управляет тегами)
drop policy if exists outfit_categories_anon_write on public.outfit_categories;
create policy outfit_categories_anon_write on public.outfit_categories
  for all to anon
  using (true) with check (true);

-- bot_preview_requests (кнопка «Превью» в конструкторе)
drop policy if exists bot_preview_requests_anon_write on public.bot_preview_requests;
create policy bot_preview_requests_anon_write on public.bot_preview_requests
  for all to anon
  using (true) with check (true);
