-- ============================================================
-- Marina Photo Bot — initial schema (no Supabase Auth)
-- ============================================================
-- Admin actions go through our own FastAPI (service_role key)
-- which bypasses RLS. Anonymous reads are allowed for published
-- content; quiz sessions are readable only when you know the UUID.

create extension if not exists "pgcrypto";

-- ---------- helpers ------------------------------------------

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------- outfits ------------------------------------------

create table if not exists public.outfits (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  colors text not null default '',
  styles text not null default '',
  seasons text not null default '',
  occasions text not null default '',
  body_types text not null default '',
  budgets text not null default '',
  shoot_types text not null default '',
  price_hint text,
  external_url text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists set_outfits_updated_at on public.outfits;
create trigger set_outfits_updated_at before update on public.outfits
  for each row execute function public.set_updated_at();

create table if not exists public.outfit_images (
  id bigint generated by default as identity primary key,
  outfit_id bigint not null references public.outfits(id) on delete cascade,
  storage_path text not null,
  caption text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists outfit_images_outfit_id_idx on public.outfit_images(outfit_id);

alter table public.outfits enable row level security;
alter table public.outfit_images enable row level security;

drop policy if exists "outfits public read" on public.outfits;
create policy "outfits public read" on public.outfits
  for select using (is_published = true);

drop policy if exists "outfit_images public read" on public.outfit_images;
create policy "outfit_images public read" on public.outfit_images
  for select using (
    exists(
      select 1 from public.outfits o
      where o.id = outfit_images.outfit_id and o.is_published = true
    )
  );

-- ---------- courses ------------------------------------------

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  short_description text,
  description text,
  cover_path text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists set_courses_updated_at on public.courses;
create trigger set_courses_updated_at before update on public.courses
  for each row execute function public.set_updated_at();

create table if not exists public.course_files (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  storage_path text not null,
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null default 0,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists course_files_course_id_idx on public.course_files(course_id);

alter table public.courses enable row level security;
alter table public.course_files enable row level security;

drop policy if exists "courses public read" on public.courses;
create policy "courses public read" on public.courses
  for select using (is_published = true);

drop policy if exists "course_files public read" on public.course_files;
create policy "course_files public read" on public.course_files
  for select using (
    exists(
      select 1 from public.courses c
      where c.id = course_files.course_id and c.is_published = true
    )
  );

-- ---------- quiz sessions ------------------------------------
-- The bot stores quiz answers here keyed by a random UUID.
-- The mini-app reads its own session by that UUID.

create table if not exists public.quiz_sessions (
  id uuid primary key default gen_random_uuid(),
  telegram_user_id bigint,
  telegram_username text,
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  consumed_at timestamptz
);
create index if not exists quiz_sessions_created_at_idx on public.quiz_sessions(created_at desc);

alter table public.quiz_sessions enable row level security;

-- Anonymous clients (mini-app) can read a row only by knowing the UUID.
-- The UUID is unguessable (random v4), so this is safe.
drop policy if exists "quiz_sessions read by id" on public.quiz_sessions;
create policy "quiz_sessions read by id" on public.quiz_sessions
  for select using (true);

-- ---------- bot users (optional analytics) -------------------

create table if not exists public.bot_users (
  telegram_id bigint primary key,
  username text,
  full_name text,
  is_premium boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.bot_users enable row level security;
-- no public policies; service_role bypasses RLS.
