-- ============================================================
-- Bot constructor schema (overhaul)
-- ============================================================
-- This migration is additive on top of 0001_init.sql and:
--   * adds bot_flows / bot_sessions / bookings / bot_events
--   * extends outfits with a free-form tags JSONB column and pinterest_url
--   * extends bot_users with cached username so /mama bookings/events lists are readable
-- All admin reads/writes go through FastAPI with the service_role key
-- (bypasses RLS). Anonymous web/bot reads remain limited to published content.

create extension if not exists "pgcrypto";

-- ---------- outfits: flexible tags + pinterest link --------------

alter table public.outfits
  add column if not exists tags jsonb not null default '{}'::jsonb,
  add column if not exists pinterest_url text;

-- Tag-bag layout: { "colors": ["black","white"], "styles": ["business"], ... }
-- The legacy comma-separated columns (colors, styles, seasons, ...) stay for
-- now so existing rows keep matching; new admin writes also fill `tags`.

-- ---------- bot_users: extend ---------------------------------

alter table public.bot_users
  add column if not exists language_code text,
  add column if not exists last_flow_id uuid,
  add column if not exists last_node_id text;

-- ---------- bot_flows: the constructor graphs -----------------

create table if not exists public.bot_flows (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  graph jsonb not null default '{"nodes": [], "edges": []}'::jsonb,
  is_published boolean not null default false,
  version integer not null default 1,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists set_bot_flows_updated_at on public.bot_flows;
create trigger set_bot_flows_updated_at before update on public.bot_flows
  for each row execute function public.set_updated_at();

create index if not exists bot_flows_is_published_idx
  on public.bot_flows(is_published) where is_published = true;

alter table public.bot_flows enable row level security;
-- no public policies; admin/mama write through service_role.

-- ---------- bot_sessions: per-user runtime state --------------
-- One row per telegram user. The engine reads/writes here every time the
-- user sends a message or clicks a button.

create table if not exists public.bot_sessions (
  telegram_id bigint primary key,
  flow_id uuid references public.bot_flows(id) on delete set null,
  current_node_id text,
  vars jsonb not null default '{}'::jsonb,
  awaiting_input boolean not null default false,
  updated_at timestamptz not null default now()
);
drop trigger if exists set_bot_sessions_updated_at on public.bot_sessions;
create trigger set_bot_sessions_updated_at before update on public.bot_sessions
  for each row execute function public.set_updated_at();

alter table public.bot_sessions enable row level security;
-- service_role only.

-- ---------- bookings: shoot requests ---------------------------

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  telegram_id bigint,
  telegram_username text,
  full_name text,
  phone text,
  preferred_date text,
  shoot_type text,
  notes text,
  payload jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists bookings_created_at_idx
  on public.bookings(created_at desc);
create index if not exists bookings_unread_idx
  on public.bookings(is_read) where is_read = false;

alter table public.bookings enable row level security;
-- service_role only.

-- ---------- bot_events: analytics + flow audit log ------------

create table if not exists public.bot_events (
  id bigint generated by default as identity primary key,
  telegram_id bigint,
  telegram_username text,
  flow_id uuid,
  node_id text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists bot_events_created_at_idx
  on public.bot_events(created_at desc);
create index if not exists bot_events_flow_node_idx
  on public.bot_events(flow_id, node_id);
create index if not exists bot_events_type_idx
  on public.bot_events(event_type);

alter table public.bot_events enable row level security;
-- service_role only.
