-- 0008_outfit_categories.sql
--
-- Справочник тэгов для образов: цвета, стили, сезоны, поводы, фигура,
-- бюджет, тип съёмки. Админ (Денис) добавляет/удаляет значения через
-- /admin/categories. Марина в Outfits видит их как multi-select-теги,
-- но в БД они по-прежнему лежат в текстовых полях outfits.* через
-- запятую — никаких ломающих миграций существующих данных.
--
-- Если таблицы ещё нет — создаём + сидим базовые значения.

create table if not exists public.outfit_categories (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in (
    'colors','styles','seasons','occasions',
    'body_types','budgets','shoot_types'
  )),
  value text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (kind, value)
);

create index if not exists outfit_categories_kind_idx
  on public.outfit_categories(kind, sort_order);

alter table public.outfit_categories enable row level security;

-- Чтение — публичное (нужно и в боте, и в мини-аппе)
drop policy if exists outfit_categories_public_read on public.outfit_categories;
create policy outfit_categories_public_read on public.outfit_categories
  for select using (true);

-- Запись — только админ или service_role
drop policy if exists outfit_categories_admin_write on public.outfit_categories;
create policy outfit_categories_admin_write on public.outfit_categories
  for all using (
    coalesce(public.app_role(), '') in ('admin','service_role')
  ) with check (
    coalesce(public.app_role(), '') in ('admin','service_role')
  );

-- ---- сиды (выполняем только если справочник пустой) ----
do $$
declare
  empty_kinds text[];
begin
  select array_agg(k) into empty_kinds
  from (
    select unnest(array[
      'colors','styles','seasons','occasions',
      'body_types','budgets','shoot_types'
    ]) as k
    except
    select distinct kind from public.outfit_categories
  ) t;

  if 'colors' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('colors','бежевый',10),('colors','белый',20),('colors','чёрный',30),
      ('colors','серый',40),('colors','коричневый',50),('colors','молочный',60),
      ('colors','оливковый',70),('colors','пастельный',80),('colors','тёмно-синий',90),
      ('colors','бордовый',100),('colors','винный',110),('colors','зелёный',120);
  end if;

  if 'styles' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('styles','casual',10),('styles','smart casual',20),('styles','классика',30),
      ('styles','романтика',40),('styles','минимализм',50),('styles','old money',60),
      ('styles','total look',70),('styles','street',80),('styles','бохо',90);
  end if;

  if 'seasons' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('seasons','весна',10),('seasons','лето',20),
      ('seasons','осень',30),('seasons','зима',40),
      ('seasons','межсезонье',50);
  end if;

  if 'occasions' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('occasions','love-story',10),('occasions','семейная съёмка',20),
      ('occasions','беременность',30),('occasions','индивидуальная',40),
      ('occasions','lookbook',50),('occasions','контент для соцсетей',60),
      ('occasions','репортаж',70),('occasions','деловая',80),
      ('occasions','свидание',90),('occasions','прогулка',100);
  end if;

  if 'body_types' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('body_types','песочные часы',10),('body_types','прямоугольник',20),
      ('body_types','груша',30),('body_types','перевёрнутый треугольник',40),
      ('body_types','яблоко',50),('body_types','plus size',60);
  end if;

  if 'budgets' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('budgets','до 5к',10),('budgets','5–15к',20),
      ('budgets','15–30к',30),('budgets','30–60к',40),
      ('budgets','60к+',50);
  end if;

  if 'shoot_types' = any(empty_kinds) then
    insert into public.outfit_categories(kind, value, sort_order) values
      ('shoot_types','студия',10),('shoot_types','улица',20),
      ('shoot_types','дома у клиента',30),('shoot_types','природа',40),
      ('shoot_types','золотой час',50),('shoot_types','зимняя на улице',60);
  end if;
end $$;
