-- 0012_child_bots.sql
-- Хранилище дочерних ботов: владелец-конструктор регистрирует токены,
-- основной процесс поллит их параллельно.

create table if not exists public.child_bots (
  id bigint generated by default as identity primary key,
  token text not null unique,
  bot_username text,
  display_name text,
  description text,
  owner_telegram_id bigint,
  is_enabled boolean not null default true,
  flow_id uuid references public.bot_flows(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists child_bots_enabled_idx
  on public.child_bots(is_enabled) where is_enabled = true;

drop trigger if exists set_child_bots_updated_at on public.child_bots;
create trigger set_child_bots_updated_at before update on public.child_bots
  for each row execute function public.set_updated_at();

alter table public.child_bots enable row level security;

drop policy if exists child_bots_admin_all on public.child_bots;
create policy child_bots_admin_all on public.child_bots
  for all to anon
  using (true) with check (true);
