create table if not exists public.pinterest_imports (
  id bigint generated by default as identity primary key,
  pinterest_url text not null,
  outfit_id bigint not null references public.outfits(id) on delete cascade,
  status text not null default 'pending', -- pending, processing, done, error
  error_text text,
  created_at timestamptz not null default now()
);

alter table public.pinterest_imports enable row level security;

create policy pinterest_imports_mama_all on public.pinterest_imports
  for all to authenticated
  using (public.app_role() in ('admin', 'mama'))
  with check (public.app_role() in ('admin', 'mama'));
